name = input("Enter your full name : ")
print(name)
print(name.upper())
print(name.lower())
print(name[0])
print(name[-1])
print(len(name))
language = input("Enter your favourite programming language : ")
print(language)
print(language.lower() == "python")